export const STRINGS = {
  // tabs bar
  "page.title.list_user": "Danh sách người dùng",
  "page.title.list_cupon": "Danh sách đổi coupon",
  "page.title.list_point": "Danh sách tích điểm",
  "page.title.list_store": "Danh sách cửa hàng",
  "page.button.down": "Tải xuống danh sách",
  "page.place.holder.search": "Tìm kiếm theo số điện thoại",
  "page.home.title": "Thiết lập tài khoản người dùng",
  "page.home.title.detail":
    "Cập nhật phân loại thành viên hoặc nhân viên của shopdunk",
  "page.home.phones": "Danh sách số điện thoại",
  "page.home.phones.comment": '(Phân tách bằng dấu ","):',
  "page.home.changeTo": "Chuyển đổi thành",
  "page.home.button.change": "Chuyển đổi",
  "enter.your.phone": "Nhập số điện thoại",
  "phone.is.required": "Số điện thoại không được để trống",
  "enter.otp": "Nhập mã OTP",
  "otp.is.required": "OTP không được để trống",
  "number.phone":"Số điện thoại",
  "otp":"Mã OTP",
  "next":"Tiếp tục",
  "text.otp":"Nhập mã OTP được gửi vào số ĐT",
  "again":"Gửi lại",
  "role.is.required":"Chọn quyền không được để trống",
  "choose.role":"Chọn quyền",
  "log.out":"Đăng xuất",
  "see.detail":"Xem chi tiết",
  "invalid_phone":"Số điện thoại sai định dạng",
  "Referrer_code":"Người giới thiệu",
  "buy":"Mua hàng",
  "change_coupon":"Đổi coupon",
  "Refferer":"Người được giới thiệu",
  "Point_9_9_2022":"Điểm 9/9/2022",
  "warning_login":"Bạn không đủ quyền đăng nhập vào hệ thống",
  "staff_shopddunk":"Nhân viên ShopDunk",
  "customer":"Khách hàng",
  "all":"Tất cả",
  "no_data":"Không có người đăng ký mới. Bạn vui lòng chọn lại thời gian và loại thành viên nhé",
  "list_store":"Danh sách cửa hàng",
  "edit":"Chỉnh sửa",
  "create_store":"+ Tạo cửa hàng mới",
  "search_store":"Tìm kiếm theo tên cửa hàng",
  "create_store_title":"Tạo cửa hàng mới",
  "edit_store_title":"Cập nhật thông tin cửa hàng",
  "delete_store":"Xoá Cửa hàng",
  "required_name_store":"Tên cửa hàng không được để trống",
  "required_province_store":"Tỉnh thành phố không được để trống",
  "required_address_store":"Địa chỉ cửa hàng không được để trống",
  "required_status_store":"Trạng thái hoạt động không được để trống",
  "required_image_store":"Ảnh cửa hàng không được để trống",
  "list_coupon_for_month":"Danh sách Coupon của tháng",
  "add_coupon":"Thêm mới Coupon",
  "required_create_coupon":"Bạn cần phải điền thông tin này để tạo coupon",
  "required_create_store":"Bạn cần phải điền thông tin này để tạo cửa hàng",
  "add_image_store":"Thêm ảnh cửa hàng",
  "save":"Lưu thay đổi",
  "no_store":"Không có cửa hàng cần tìm kiếm",
  "no_coupon":"Không có người đổi coupon mới. Bạn vui lòng chọn lại thời gian và loại thành viên nhé",
  "no_point":"Không có người tích điểm mới. Bạn vui lòng chọn lại thời gian và loại thành viên nhé",

};
export const ENVIRONMENTS = {
  API_URL: process.env.NEXT_PUBLIC_API_URL,
};

export const API_PATH={
  LOGIN:"/auth/login"
}